# JDE credentials / connection
config.jdeUser=JDE
config.jdePassword=****
config.jdeEnvironment=JDV920
config.jdeRole=*ALL

# Atina microservice endpoint (host/IP + port)
config.microServiceName=67.207.85.5
config.microServicePort=8077

config.jdeUserMulesoft=MULESOFT